(hall-description
  (name "guile-utils")
  (prefix "")
  (version "0.1")
  (author "Tim Van den Langenbergh")
  (copyright (2021))
  (synopsis "Miscellaneous utilities for GNU Guile.")
  (description "Various useful functions for common problems.")
  (home-page "")
  (license gpl3+)
  (dependencies `())
  (files (libraries
          ((scheme-file "utils")))
		 (programs ((directory "scripts" ())))
         (tests ((directory "tests" ())))
         (documentation
           ((org-file "README")
            (symlink "README" "README.org")
            (text-file "HACKING")
            (text-file "COPYING")
            (directory "doc" ((texi-file "guile-utils")))))
         (infrastructure
           ((scheme-file "guix")
            (text-file ".gitignore")
            (scheme-file "hall")))))
