
\input texinfo
@c -*-texinfo-*-

@c %**start of header
@setfilename guile-utils.info
@documentencoding UTF-8
@settitle Guile-Utils Reference Manual
@c %**end of header

@copying
Copyright @copyright{} 2021 Tim Van den Langenbergh @email{tmt_vdl@@gmx.com}

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled ``GNU Free
Documentation License''.

A copy of the license is also available from the Free Software
Foundation Web site at @url{http://www.gnu.org/licenses/fdl.html}.
@end copying

@dircategory The Algorithmic Language Scheme
@direntry
* Guile-Utils: (guile-utils).   Miscellaneous utilities for GNU Guile.
@end direntry

@titlepage
@title The Guile-Utils Manual
@author Tim Van den Langenbergh

@page
@vskip 0pt plus 1filll
Edition @value{EDITION} @*
@value{UPDATED} @*

@insertcopying
@end titlepage

@contents

@c *********************************************************************
@node Top
@top Guile-Utils

This document describes Guile-Utils version @value{VERSION}.

@menu
* Introduction::                Why Guile-Utils?
* Usage::                       How to use Guile-Utils?
@end menu

@c *********************************************************************
@node Introduction
@chapter Introduction

Guile-utils is a library containing various useful procedures for solving
(more-or-less) common problems.

@node Usage
@chapter Usage

After installing Guile-utils you can import it like so:

@example
(use-modules (utils))
@end example

@bye
